apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-two
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: guestbook-two
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/KipsasJaujoj/argocd-example-apps
    targetRevision: HEAD
  # syncPolicy: {}
  syncPolicy:
    automated:
      prune: true
